`import React from 'react';
import './__tpl_name__.__tpl_cfg_css__';

export default function __tpl_name__(props) {
	return <div className='__tpl_name__'>
		<h3>__tpl_name__</h3>
		<small>Generated by @lrw/mogen</small>
	</div>
};`