`import React from 'react';
import './__tpl_name__.__tpl_cfg_css__';

const propTypes = {
	
};

const __tpl_name__ = (props) => {
	return <div className='__tpl_name__'>
		<h3>Stateless component: __tpl_name__</h3>
		<p>Generated by react-mogen</p>
	</div>
};

__tpl_name__.propTypes = propTypes;
export default __tpl_name__;`