"use strict";

"import React from 'react';\nimport './__tpl_name__.__tpl_cfg_css__';\n\nconst propTypes = {\n\t\n};\n\nconst __tpl_name__ = (props) => {\n\treturn <div className='__tpl_name__'>\n\t\t<h3>Stateless component: __tpl_name__</h3>\n\t\t<p>Generated by react-mogen</p>\n\t</div>\n};\n\n__tpl_name__.propTypes = propTypes;\nexport default __tpl_name__;";